name: Deploy VPC

on:
  push:
    paths:
      - 'modules/vpc/**'
      - '.github/workflows/01-vpc.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-north-1

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - run: terraform init

      - run: terraform plan -target=module.vpc

      - run: terraform apply -auto-approve -target=module.vpc
