name: Deploy RDS

on:
  push:
    paths:
      - 'modules/rds/**'
      - '.github/workflows/03-rds.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-north-1
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_tags: '{"Environment":"dev","Owner":"kabiru","Project":"terraform-series"}'
      TF_VAR_ec2_key_pair_name: ${{ secrets.EC2_KEY_PAIR_NAME }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - run: terraform init

      - run: terraform plan -target=module.rds

      - run: terraform apply -auto-approve -target=module.rds
